PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

SELECT ?o (COUNT(?o) as ?oCount)
WHERE
{
    graph ?g { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o} .
}
GROUP BY ?o

