direction: right

NSDF: National Science Data Fabric
DC: Data Commons
NC: NSDF Catalog
WOD: World Ocean Database
OCD: Open Core Data
DeC: DeCODER

NSDF -> NC
NC -> DeC
NC -> DC

WOD -> OIH
WOD -> DeC
WOD -> DC

OCD -> DeC