diretion: right

NSDF: National Science Data FAbric
NC: NSDF Catalog

NSDF -> NC

// Need the steps
// 1) read the metadata
// 2) inspect the distribution (optional)
// 3) write record to parquet
// 4) read and regroup

// New images
// need to get the core NC fields and map to schema.org
// and add in what I would think useful.


